### ISSUE TITLE
Is there a secio formal spec

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p-secio#13]
Is there a formal spec describing the secio protocol in detail?

**Comment by ghost** [comment]
Unfortunately not yet :(

[go-libp2p-secio/protocol.go](https://github.com/libp2p/go-libp2p-secio/blob/master/protocol.go) is the closest we've got.

**Comment by daviddias** [comment]
Existing docs:

- https://github.com/libp2p/js-libp2p/tree/master/examples/encrypted-communications
- https://github.com/auditdrivencrypto/secure-channel/blob/master/prior-art.md#ipfss-secure-channel

**Comment by Stebalien** [comment]
See: https://github.com/libp2p/specs/pull/106
