### ISSUE TITLE
Protobuf Propose.pubkey can be defined as crypto.pb.PublicKey

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/go-libp2p-secio#53]
The protobuf `Propose.pubkey` is defined as `bytes` while it is serialized protobuf `crypto.pb.PublicKey` message. 
It could be defined in the following way for better clarity: 
```proto
import "crypto.proto";

message Propose {
	optional bytes rand = 1;
	optional crypto.pb.PublicKey pubkey = 2;
	optional string exchanges = 3;
	optional string ciphers = 4;
	optional string hashes = 5;
}
```
Duplicate in spec repo: https://github.com/libp2p/specs/issues/193

**Comment by Stebalien** [comment]
(secio has been deprecated)
