### ISSUE TITLE
AES-GCM support

### ISSUE THREAD

**Issue by kingwel-xie** [libp2p/go-libp2p-secio#66]
secio is bad at performance due to AES-CTR+SHA. I added GCM support and did some performance test. More details can be found at https://blog.csdn.net/m0_37889044/article/details/104466718

Wonder if the code contribution is accepted, and how. I'm completely a new guy to libp2p...

**Comment by Stebalien** [comment]
That's really cool! 

Unfortunately, we're actually moving to switch _away_ from SECIO, to [Noise](https://github.com/libp2p/go-libp2p-noise) and [TLS1.3](https://github.com/libp2p/go-libp2p-tls/) so there's little to be gained from improving the performance of SECIO (unless something goes terribly wrong with the upgrade).

On the other hand, we'll definitely keep this in mind if we ever decide to introduce a SECIO 2.0.

**Comment by kingwel-xie** [comment]
fair enough! Look forward to the update!

**Comment by Stebalien** [comment]
(secio has now been officially deprecated and replaced with noise and TLS1.3)
